name: Build npm release

variables:
  esy__ci_cache_version: v1    # this is available to all jobs in env as $ESY__CI_CACHE_VERSION or in azure config as $(esy__ci_cache_version)

trigger:
  - master
  - global
  - release-*
  - releases-*
  - feature-*

jobs:
  - template: .ci-self/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-latest